name: Quality Assurance

on:
    push:
        paths:
            - '**workflows/qa.yml'
            - '**.php'
            - '**phpcs.xml.dist'
            - '**phpunit.xml.dist'
            - '**psalm.xml'
            - '**composer.json'
    pull_request:
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    static-qa:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip qa') }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: 8.0
                    coverage: none
                    tools: cs2pr

            -   name: Install dependencies
                uses: ramsey/composer-install@v2

            -   name: Check code styles
                run: ./vendor/bin/phpcs --report=checkstyle -q | cs2pr

            -   name: Static analysis via Psalm
                run: ./vendor/bin/psalm --output-format=github

    unit-tests:
        runs-on: ubuntu-latest
        if: ${{ !contains(github.event.head_commit.message, 'skip tests') }}
        env:
            USE_COVERAGE: 'no'
        strategy:
            fail-fast: false
            matrix:
                php-ver: [ '8.0', '8.1' ]
                dependency-versions: [ 'lowest', 'highest' ]
                experimental: [ false ]
                include:
                    -   php-ver: '8.2'
                        dependency-versions: 'highest'
                        experimental: true
        continue-on-error: ${{ matrix.experimental == true }}
        steps:
            -   name: Update "USE_COVERAGE" env var based on matrix
                if: ${{ matrix.php-ver == '8.0' && matrix.dependency-versions == 'highest' }}
                run: echo "USE_COVERAGE=yes" >> $GITHUB_ENV

            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-ver }}
                    ini-values: zend.assertions=1, error_reporting=-1, display_errors=On
                    coverage: ${{ ((env.USE_COVERAGE == 'yes') && 'xdebug') || 'none' }}
                    tools: cs2pr

            -   name: Install parallel-lint
                if: ${{ matrix.dependency-versions == 'highest' }}
                run: composer require php-parallel-lint/php-parallel-lint:^1.3.1 --dev --no-update

            -   name: Remove unused dev dependencies that conflict with PHP version
                run: composer remove vimeo/psalm inpsyde/php-coding-standards --dev --no-update

            -   name: Install dependencies
                uses: ramsey/composer-install@v2
                with:
                    dependency-versions: ${{ matrix.dependency-versions }}

            -   name: Lint PHP sources
                if: ${{ matrix.dependency-versions == 'highest' }}
                run: ./vendor/bin/parallel-lint ./src/ ./inc/ --checkstyle | cs2pr

            -   name: Run unit tests
                run: ./vendor/bin/phpunit ${{ ((env.USE_COVERAGE == 'yes') && '--coverage-clover=coverage.xml') || '--no-coverage' }}

            -   name: Update codecov.io
                uses: codecov/codecov-action@v2
                if: ${{ env.USE_COVERAGE == 'yes' }}
                with:
                    file: ./coverage.xml
